apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  labels:
    cluster.open-cluster-management.io/backup: submariner
  name: submariner-broker
  namespace: {submariner}-{cluster-a-cluster-b}-{broker}
spec:
  globalnetCIDRRange: 242.0.0.0/8
  globalnetEnabled: true

